name: Vue App, Build, Test and Deploy

on:

  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extraction du repository
        uses: actions/checkout@v4

      - name: Installation de Node.Js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Installation des dépendances
        run: npm i

      - name: Build du Project
        run: npm run build